
package view;

import classes.Cliente;
import classes.Veiculo;
import classes.Locadora;
import connection.ClienteDAO;
import connection.LocadoraDAO;
import connection.VeiculoDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import validacao.ValidaC;
import validacao.ValidaVeiculo;


public class PrincipalCliente extends javax.swing.JFrame {

    public PrincipalCliente(Cliente c) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));
        
        setPerfil(c);
        
        readJTable();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPMeuPerfil = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLNome1 = new javax.swing.JLabel();
        nomePerfilCliente = new javax.swing.JTextField();
        jLEmail1 = new javax.swing.JLabel();
        emailPerfilCliente = new javax.swing.JTextField();
        jLTelefonePerfil = new javax.swing.JLabel();
        telefonePerfilCliente = new javax.swing.JFormattedTextField();
        jLSenha1 = new javax.swing.JLabel();
        senhaPerfilCliente = new javax.swing.JPasswordField();
        excluirPerfil = new javax.swing.JButton();
        atualizarPerfil = new javax.swing.JButton();
        jLNome2 = new javax.swing.JLabel();
        idPerfilCliente = new javax.swing.JLabel();
        jPVeiculos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTFbuscarMarca = new javax.swing.JTextField();
        buscarMarca = new javax.swing.JButton();
        buscarCarros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFbuscarModelo = new javax.swing.JTextField();
        buscarModelo = new javax.swing.JButton();
        bucarTodos = new javax.swing.JButton();
        buscarMotocicletas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPLocadora = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTFbuscarMarca1 = new javax.swing.JTextField();
        buscarMarca1 = new javax.swing.JButton();
        buscarCarros1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFbuscarModelo1 = new javax.swing.JTextField();
        buscarModelo1 = new javax.swing.JButton();
        bucarTodos1 = new javax.swing.JButton();
        buscarMotocicletas1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMMeuPerfil = new javax.swing.JMenu();
        jMPesquisarVeiculo = new javax.swing.JMenu();
        jMPesquisarLocadora = new javax.swing.JMenu();
        jMSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jLayeredPane3.setPreferredSize(new java.awt.Dimension(266, 253));

        jLNome1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLNome1.setText("Nome");

        jLEmail1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLEmail1.setText("E-mail");

        jLTelefonePerfil.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLTelefonePerfil.setText("Telefone");

        try {
            telefonePerfilCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLSenha1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLSenha1.setText("Senha");

        excluirPerfil.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        excluirPerfil.setText("EXCLUIR CONTA");
        excluirPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPerfilActionPerformed(evt);
            }
        });

        atualizarPerfil.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        atualizarPerfil.setText("ATUALIZAR");
        atualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPerfilActionPerformed(evt);
            }
        });

        jLNome2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLNome2.setText("ID");

        idPerfilCliente.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N

        jLayeredPane3.setLayer(jLNome1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nomePerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLEmail1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(emailPerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLTelefonePerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(telefonePerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLSenha1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(senhaPerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(excluirPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(atualizarPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLNome2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(idPerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTelefonePerfil)
                            .addComponent(jLSenha1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(atualizarPerfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(excluirPerfil)
                                .addGap(107, 107, 107))
                            .addComponent(senhaPerfilCliente)
                            .addComponent(telefonePerfilCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome1)
                            .addComponent(jLEmail1)
                            .addComponent(jLNome2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailPerfilCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                            .addComponent(nomePerfilCliente))))
                .addGap(371, 371, 371))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome2)
                    .addComponent(idPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome1)
                    .addComponent(nomePerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEmail1)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(emailPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefonePerfil)
                            .addComponent(telefonePerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSenha1))
                .addGap(50, 50, 50)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarPerfil)
                    .addComponent(excluirPerfil))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMeuPerfilLayout = new javax.swing.GroupLayout(jPMeuPerfil);
        jPMeuPerfil.setLayout(jPMeuPerfilLayout);
        jPMeuPerfilLayout.setHorizontalGroup(
            jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMeuPerfilLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
                .addGap(230, 230, 230))
        );
        jPMeuPerfilLayout.setVerticalGroup(
            jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMeuPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPMeuPerfil, "meuPerfil");

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        buscarMarca.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarMarca.setText("BUSCAR");
        buscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMarcaActionPerformed(evt);
            }
        });

        buscarCarros.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarCarros.setText("Ver somente carros");
        buscarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCarrosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel1.setText("Buscar por Marca");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel2.setText("Buscar por Modelo");

        buscarModelo.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarModelo.setText("BUSCAR");
        buscarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarModeloActionPerformed(evt);
            }
        });

        bucarTodos.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bucarTodos.setText("Ver todos os veículos");
        bucarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarTodosActionPerformed(evt);
            }
        });

        buscarMotocicletas.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarMotocicletas.setText("Ver somente motocicletas");
        buscarMotocicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMotocicletasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFbuscarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarModelo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTFbuscarMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarMarca))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(buscarMotocicletas)
                        .addGap(44, 44, 44)
                        .addComponent(buscarCarros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(bucarTodos)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bucarTodos)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMotocicletas)
                    .addComponent(buscarCarros))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buscarMarca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFbuscarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarModelo))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Veículo", "Marca", "Modelo", "Preço", "Ano", "Cor", "Combustível", "Motor", "Placa"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPVeiculosLayout = new javax.swing.GroupLayout(jPVeiculos);
        jPVeiculos.setLayout(jPVeiculosLayout);
        jPVeiculosLayout.setHorizontalGroup(
            jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVeiculosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPVeiculosLayout.setVerticalGroup(
            jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVeiculosLayout.createSequentialGroup()
                .addGroup(jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVeiculosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPVeiculosLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelPrincipal.add(jPVeiculos, "pesquisarVeiculos");

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel2FocusLost(evt);
            }
        });

        jTFbuscarMarca1.setEnabled(false);

        buscarMarca1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarMarca1.setText("BUSCAR");
        buscarMarca1.setEnabled(false);
        buscarMarca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMarca1ActionPerformed(evt);
            }
        });

        buscarCarros1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarCarros1.setText("Ver somente carros");
        buscarCarros1.setEnabled(false);
        buscarCarros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCarros1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel3.setText("Buscar por Marca");
        jLabel3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel4.setText("Buscar por Modelo");
        jLabel4.setEnabled(false);

        jTFbuscarModelo1.setEnabled(false);

        buscarModelo1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarModelo1.setText("BUSCAR");
        buscarModelo1.setEnabled(false);
        buscarModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarModelo1ActionPerformed(evt);
            }
        });

        bucarTodos1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bucarTodos1.setText("Ver todos os veículos");
        bucarTodos1.setEnabled(false);
        bucarTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarTodos1ActionPerformed(evt);
            }
        });

        buscarMotocicletas1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        buscarMotocicletas1.setText("Ver somente motocicletas");
        buscarMotocicletas1.setEnabled(false);
        buscarMotocicletas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMotocicletas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFbuscarModelo1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarModelo1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTFbuscarMarca1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarMarca1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(buscarMotocicletas1)
                        .addGap(44, 44, 44)
                        .addComponent(buscarCarros1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(bucarTodos1)
                .addGap(147, 147, 147))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bucarTodos1)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMotocicletas1)
                    .addComponent(buscarCarros1))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscarMarca1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFbuscarModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarModelo1))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CNPJ", "Nome", "Telefone", "E-mail"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPLocadoraLayout = new javax.swing.GroupLayout(jPLocadora);
        jPLocadora.setLayout(jPLocadoraLayout);
        jPLocadoraLayout.setHorizontalGroup(
            jPLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLocadoraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPLocadoraLayout.setVerticalGroup(
            jPLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLocadoraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelPrincipal.add(jPLocadora, "pesquisarLocadora");

        jMMeuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon25.png"))); // NOI18N
        jMMeuPerfil.setText("Meu perfil");
        jMMeuPerfil.setToolTipText("");
        jMMeuPerfil.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMMeuPerfil.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMMeuPerfil.setRolloverEnabled(true);
        jMMeuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMMeuPerfilMouseClicked(evt);
            }
        });
        jMenuBar.add(jMMeuPerfil);

        jMPesquisarVeiculo.setText("Pesquisar Veiculo");
        jMPesquisarVeiculo.setContentAreaFilled(false);
        jMPesquisarVeiculo.setFocusable(false);
        jMPesquisarVeiculo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMPesquisarVeiculo.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMPesquisarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPesquisarVeiculoMouseClicked(evt);
            }
        });
        jMenuBar.add(jMPesquisarVeiculo);

        jMPesquisarLocadora.setText("Pesquisar Locadora");
        jMPesquisarLocadora.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMPesquisarLocadora.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMPesquisarLocadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPesquisarLocadoraMouseClicked(evt);
            }
        });
        jMenuBar.add(jMPesquisarLocadora);

        jMSobre.setText("Sobre");
        jMSobre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMSobre.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSobreMouseClicked(evt);
            }
        });
        jMenuBar.add(jMSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMMeuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMMeuPerfilMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "meuPerfil");
        jMMeuPerfil.setSelected(false);
    }//GEN-LAST:event_jMMeuPerfilMouseClicked

    private void jMPesquisarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPesquisarVeiculoMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "pesquisarVeiculos");
        jMPesquisarVeiculo.setSelected(false);
    }//GEN-LAST:event_jMPesquisarVeiculoMouseClicked

    private void jMPesquisarLocadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPesquisarLocadoraMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "pesquisarLocadora");
        jMPesquisarLocadora.setSelected(false);
    }//GEN-LAST:event_jMPesquisarLocadoraMouseClicked

    private void jMSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSobreMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "sobre");
        jMSobre.setSelected(false);
       
    }//GEN-LAST:event_jMSobreMouseClicked

    private void atualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPerfilActionPerformed
 
        ClienteDAO dao = new ClienteDAO();
        Cliente c = new Cliente();
        
        c.setNome(nomePerfilCliente.getText());
        c.setEmail(emailPerfilCliente.getText());
      //  c.setCpf(cpfPerfilCliente.getText());
        c.setTelefone(telefonePerfilCliente.getText());
        c.setSenha(senhaPerfilCliente.getText());
        c.setId(Integer.parseInt(idPerfilCliente.getText()));
        //JOptionPane.showMessageDialog(null, c.getCpf() + " ");
        
        dao.update(c);

    }//GEN-LAST:event_atualizarPerfilActionPerformed

    private void excluirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirPerfilActionPerformed

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost

    }//GEN-LAST:event_jPanel1FocusLost

    private void buscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMarcaActionPerformed
        readJTableForMarca(jTFbuscarMarca.getText());
    }//GEN-LAST:event_buscarMarcaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

    }//GEN-LAST:event_jTable1KeyReleased

    private void buscarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCarrosActionPerformed
         readJTableForCarros();
    }//GEN-LAST:event_buscarCarrosActionPerformed

    private void buscarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarModeloActionPerformed
         readJTableForModelo(jTFbuscarModelo.getText());
    }//GEN-LAST:event_buscarModeloActionPerformed

    private void bucarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarTodosActionPerformed
        readJTable();
    }//GEN-LAST:event_bucarTodosActionPerformed

    private void buscarMotocicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMotocicletasActionPerformed
        readJTableForMotocicleta();
    }//GEN-LAST:event_buscarMotocicletasActionPerformed

    private void buscarMarca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMarca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMarca1ActionPerformed

    private void buscarCarros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCarros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCarros1ActionPerformed

    private void buscarModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarModelo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarModelo1ActionPerformed

    private void bucarTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarTodos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bucarTodos1ActionPerformed

    private void buscarMotocicletas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMotocicletas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMotocicletas1ActionPerformed

    private void jPanel2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2FocusLost

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente c = new Cliente();
                new PrincipalCliente(c).setVisible(true);
             //   testarPerfil();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarPerfil;
    private javax.swing.JButton bucarTodos;
    private javax.swing.JButton bucarTodos1;
    private javax.swing.JButton buscarCarros;
    private javax.swing.JButton buscarCarros1;
    private javax.swing.JButton buscarMarca;
    private javax.swing.JButton buscarMarca1;
    private javax.swing.JButton buscarModelo;
    private javax.swing.JButton buscarModelo1;
    private javax.swing.JButton buscarMotocicletas;
    private javax.swing.JButton buscarMotocicletas1;
    private javax.swing.JTextField emailPerfilCliente;
    private javax.swing.JButton excluirPerfil;
    private javax.swing.JLabel idPerfilCliente;
    private javax.swing.JLabel jLEmail1;
    private javax.swing.JLabel jLNome1;
    private javax.swing.JLabel jLNome2;
    private javax.swing.JLabel jLSenha1;
    private javax.swing.JLabel jLTelefonePerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenu jMMeuPerfil;
    private javax.swing.JMenu jMPesquisarLocadora;
    private javax.swing.JMenu jMPesquisarVeiculo;
    private javax.swing.JMenu jMSobre;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPLocadora;
    private javax.swing.JPanel jPMeuPerfil;
    private javax.swing.JPanel jPVeiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFbuscarMarca;
    private javax.swing.JTextField jTFbuscarMarca1;
    private javax.swing.JTextField jTFbuscarModelo;
    private javax.swing.JTextField jTFbuscarModelo1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nomePerfilCliente;
    private javax.swing.JPasswordField senhaPerfilCliente;
    private javax.swing.JFormattedTextField telefonePerfilCliente;
    // End of variables declaration//GEN-END:variables

    public void limpar(){
      
    }


      public void readJTable(){
          
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setNumRows(0);
            VeiculoDAO VeiculoDao = new VeiculoDAO();
            
            for(Veiculo v: VeiculoDao.read())
                // pegar valor da lista e ir 'setando' no veiculo
                
                modelo.addRow(new Object[]{
                    v.getId(),
                    v.getVeiculo(),
                    v.getMarca(),
                    v.getModelo(),
                    v.getPrecoDia(),
                    v.getAno(),
                    v.getCor(),
                    v.getCombustivel(),
                    v.getMotor(),
                    v.getPlaca()
                });
                  DefaultTableModel a = (DefaultTableModel) jTable1.getModel();
      }

    public void readJTableForMarca(String marca) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForMarca(marca).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
    public void readJTableForModelo(String modelo) {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForModelo(modelo).forEach((v) -> {
            model.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     public void readJTableForCarros() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForCarros().forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     
     public void readJTableForMotocicleta() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForMotocicleta().forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
    public void readJTableForDescLocadora(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        LocadoraDAO ldao = new LocadoraDAO();

        ldao.readForDescLocadora(desc).forEach((l) -> {
            modelo.addRow(new Object[]{
                
                l.getId(),
                l.getCnpj(),
                l.getNome(),
                l.getSenha(),
                l.getEmail(),
                l.getTelefone()
                
            });
        });

    }
    public void setPerfil(Cliente c){
        
        nomePerfilCliente.setText(c.getNome());
        emailPerfilCliente.setText(c.getEmail());
        telefonePerfilCliente.setText(c.getTelefone());
        senhaPerfilCliente.setText(c.getSenha());
        idPerfilCliente.setText(String.valueOf(c.getId()));
        
    }

}
