
package view;

import model.bean.Cliente;
import model.bean.Veiculo;
import model.bean.Locadora;
import modelo.dao.ClienteDAO;
import modelo.dao.LocadoraDAO;
import modelo.dao.VeiculoDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class PrincipalCliente extends javax.swing.JFrame {

    
    public static int id = 0; 
     
    public PrincipalCliente(Cliente c) {
        id = c.getId();
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        jTableVeiculo.setRowSorter(new TableRowSorter(modelo));
        
        setPerfil(c);
        readJTableVeiculo();
        readJTableLocadora();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPVeiculos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTFbuscarMarca = new javax.swing.JTextField();
        buscarMarca = new javax.swing.JButton();
        buscarCarros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFbuscarModelo = new javax.swing.JTextField();
        buscarModelo = new javax.swing.JButton();
        bucarTodosVeiculos = new javax.swing.JButton();
        buscarMotocicletas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFbuscarIdVeiculo = new javax.swing.JTextField();
        buscarIdVeiculo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFbuscarIdLocadora = new javax.swing.JTextField();
        buscarIdLocadora = new javax.swing.JButton();
        jTFbuscarAno = new javax.swing.JTextField();
        buscarAno = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTFbuscarCor = new javax.swing.JTextField();
        buscarCor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jPLocadora = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTFbuscarLocadoraNome = new javax.swing.JTextField();
        buscarLocadoraNome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFbuscarLocadoraCNPJ = new javax.swing.JTextField();
        buscarLocadoraCNPJ = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTFBuscarLocadoraIdLocadora = new javax.swing.JTextField();
        BuscarLocadoraLocadoraId = new javax.swing.JButton();
        bucarTodasLocadoras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLocadora = new javax.swing.JTable();
        jPMeuPerfil = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLNome1 = new javax.swing.JLabel();
        nomePerfilCliente = new javax.swing.JTextField();
        jLEmail1 = new javax.swing.JLabel();
        emailPerfilCliente = new javax.swing.JTextField();
        jLTelefonePerfil = new javax.swing.JLabel();
        telefonePerfilCliente = new javax.swing.JFormattedTextField();
        jLSenha1 = new javax.swing.JLabel();
        senhaPerfilCliente = new javax.swing.JPasswordField();
        excluirPerfil = new javax.swing.JButton();
        atualizarPerfil = new javax.swing.JButton();
        jLNome2 = new javax.swing.JLabel();
        idPerfilCliente = new javax.swing.JLabel();
        jPSobre = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMMeuPerfil = new javax.swing.JMenu();
        jMPesquisarVeiculo = new javax.swing.JMenu();
        jMPesquisarLocadora = new javax.swing.JMenu();
        jMSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jTFbuscarMarca.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarMarcaKeyPressed(evt);
            }
        });

        buscarMarca.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarMarca.setText("BUSCAR");
        buscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMarcaActionPerformed(evt);
            }
        });

        buscarCarros.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarCarros.setText("Ver somente carros");
        buscarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCarrosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel1.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel2.setText("Modelo");

        jTFbuscarModelo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarModeloKeyPressed(evt);
            }
        });

        buscarModelo.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarModelo.setText("BUSCAR");
        buscarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarModeloActionPerformed(evt);
            }
        });

        bucarTodosVeiculos.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        bucarTodosVeiculos.setText("Ver todos os veículos");
        bucarTodosVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarTodosVeiculosActionPerformed(evt);
            }
        });

        buscarMotocicletas.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarMotocicletas.setText("Ver somente motocicletas");
        buscarMotocicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMotocicletasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel7.setText("Id do Veiculo");

        jTFbuscarIdVeiculo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarIdVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarIdVeiculoKeyPressed(evt);
            }
        });

        buscarIdVeiculo.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarIdVeiculo.setText("BUSCAR");
        buscarIdVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdVeiculoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel8.setText("Id da Locadora");

        jTFbuscarIdLocadora.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarIdLocadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarIdLocadoraKeyPressed(evt);
            }
        });

        buscarIdLocadora.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarIdLocadora.setText("BUSCAR");
        buscarIdLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdLocadoraActionPerformed(evt);
            }
        });

        jTFbuscarAno.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarAnoKeyPressed(evt);
            }
        });

        buscarAno.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarAno.setText("BUSCAR");
        buscarAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAnoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel10.setText("Ano");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel11.setText("Cor");

        jTFbuscarCor.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarCorKeyPressed(evt);
            }
        });

        buscarCor.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarCor.setText("BUSCAR");
        buscarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buscarMotocicletas)
                .addGap(18, 18, 18)
                .addComponent(buscarCarros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFbuscarCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFbuscarModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarModelo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFbuscarMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarMarca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFbuscarIdVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarIdVeiculo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFbuscarIdLocadora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarIdLocadora))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFbuscarAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarAno)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bucarTodosVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bucarTodosVeiculos)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMotocicletas)
                    .addComponent(buscarCarros))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFbuscarIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarIdVeiculo))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFbuscarIdLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarIdLocadora))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMarca)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFbuscarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarModelo))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(buscarAno))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTFbuscarCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCor))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTableVeiculo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Veiculo", "Id Locadora", "Veículo", "Marca", "Modelo", "Preço", "Ano", "Cor", "Combustível", "Motor", "Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableVeiculo);

        javax.swing.GroupLayout jPVeiculosLayout = new javax.swing.GroupLayout(jPVeiculos);
        jPVeiculos.setLayout(jPVeiculosLayout);
        jPVeiculosLayout.setHorizontalGroup(
            jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVeiculosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPVeiculosLayout.setVerticalGroup(
            jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVeiculosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanelPrincipal.add(jPVeiculos, "pesquisarVeiculos");

        jPLocadora.setRequestFocusEnabled(false);

        jTFbuscarLocadoraNome.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarLocadoraNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarLocadoraNomeKeyPressed(evt);
            }
        });

        buscarLocadoraNome.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarLocadoraNome.setText("BUSCAR");
        buscarLocadoraNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLocadoraNomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel4.setText("CNPJ");

        jTFbuscarLocadoraCNPJ.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFbuscarLocadoraCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFbuscarLocadoraCNPJKeyPressed(evt);
            }
        });

        buscarLocadoraCNPJ.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        buscarLocadoraCNPJ.setText("BUSCAR");
        buscarLocadoraCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLocadoraCNPJActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        jLabel18.setText("Id da Locadora");

        jTFBuscarLocadoraIdLocadora.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTFBuscarLocadoraIdLocadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFBuscarLocadoraIdLocadoraKeyPressed(evt);
            }
        });

        BuscarLocadoraLocadoraId.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        BuscarLocadoraLocadoraId.setText("BUSCAR");
        BuscarLocadoraLocadoraId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLocadoraLocadoraIdActionPerformed(evt);
            }
        });

        bucarTodasLocadoras.setFont(new java.awt.Font("Noto Sans", 3, 15)); // NOI18N
        bucarTodasLocadoras.setText("Ver todas as Locadoras");
        bucarTodasLocadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarTodasLocadorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFbuscarLocadoraCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarLocadoraCNPJ))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFbuscarLocadoraNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarLocadoraNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFBuscarLocadoraIdLocadora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarLocadoraLocadoraId))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bucarTodasLocadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bucarTodasLocadoras)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTFBuscarLocadoraIdLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarLocadoraLocadoraId))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarLocadoraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarLocadoraNome)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFbuscarLocadoraCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarLocadoraCNPJ))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTableLocadora.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTableLocadora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Locadora", "Nome", "CNPJ", "Telefone", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLocadora.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableLocadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTableLocadora);

        javax.swing.GroupLayout jPLocadoraLayout = new javax.swing.GroupLayout(jPLocadora);
        jPLocadora.setLayout(jPLocadoraLayout);
        jPLocadoraLayout.setHorizontalGroup(
            jPLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLocadoraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPLocadoraLayout.setVerticalGroup(
            jPLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLocadoraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanelPrincipal.add(jPLocadora, "pesquisarLocadora");

        jLayeredPane3.setPreferredSize(new java.awt.Dimension(266, 253));

        jLNome1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLNome1.setText("Nome");

        jLEmail1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLEmail1.setText("E-mail");

        jLTelefonePerfil.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLTelefonePerfil.setText("Telefone");

        try {
            telefonePerfilCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLSenha1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLSenha1.setText("Senha");

        excluirPerfil.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        excluirPerfil.setText("EXCLUIR CONTA");
        excluirPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPerfilActionPerformed(evt);
            }
        });

        atualizarPerfil.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        atualizarPerfil.setText("ATUALIZAR");
        atualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPerfilActionPerformed(evt);
            }
        });

        jLNome2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLNome2.setText("ID");

        idPerfilCliente.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N

        jLayeredPane3.setLayer(jLNome1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nomePerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLEmail1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(emailPerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLTelefonePerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(telefonePerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLSenha1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(senhaPerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(excluirPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(atualizarPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLNome2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(idPerfilCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTelefonePerfil)
                    .addComponent(jLSenha1))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaPerfilCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonePerfilCliente)))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNome1)
                    .addComponent(jLNome2)
                    .addComponent(jLEmail1))
                .addGap(47, 47, 47)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomePerfilCliente)
                    .addComponent(idPerfilCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailPerfilCliente)))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(atualizarPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(excluirPerfil)
                .addGap(99, 99, 99))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNome2)
                    .addComponent(idPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome1)
                    .addComponent(nomePerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail1))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefonePerfil)
                    .addComponent(telefonePerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaPerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSenha1))
                .addGap(45, 45, 45)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarPerfil)
                    .addComponent(excluirPerfil))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPMeuPerfilLayout = new javax.swing.GroupLayout(jPMeuPerfil);
        jPMeuPerfil.setLayout(jPMeuPerfilLayout);
        jPMeuPerfilLayout.setHorizontalGroup(
            jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMeuPerfilLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPMeuPerfilLayout.setVerticalGroup(
            jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMeuPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPMeuPerfil, "meuPerfil");

        jLabel5.setFont(new java.awt.Font("Noto Serif", 3, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpeg"))); // NOI18N
        jLabel5.setText("AUTOVERHUUR");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel6.setText("Nós somos a Autoverhuur. Esse nome vem do holandês e significa aluguel de veiculos.");

        javax.swing.GroupLayout jPSobreLayout = new javax.swing.GroupLayout(jPSobre);
        jPSobre.setLayout(jPSobreLayout);
        jPSobreLayout.setHorizontalGroup(
            jPSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSobreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPSobreLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addContainerGap(598, Short.MAX_VALUE))
        );
        jPSobreLayout.setVerticalGroup(
            jPSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSobreLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPSobre, "sobre");

        jMMeuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon25.png"))); // NOI18N
        jMMeuPerfil.setText("Meu perfil");
        jMMeuPerfil.setToolTipText("");
        jMMeuPerfil.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMMeuPerfil.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMMeuPerfil.setRolloverEnabled(true);
        jMMeuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMMeuPerfilMouseClicked(evt);
            }
        });
        jMenuBar.add(jMMeuPerfil);

        jMPesquisarVeiculo.setText("Pesquisar Veiculo");
        jMPesquisarVeiculo.setContentAreaFilled(false);
        jMPesquisarVeiculo.setFocusable(false);
        jMPesquisarVeiculo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMPesquisarVeiculo.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMPesquisarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPesquisarVeiculoMouseClicked(evt);
            }
        });
        jMenuBar.add(jMPesquisarVeiculo);

        jMPesquisarLocadora.setText("Pesquisar Locadora");
        jMPesquisarLocadora.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMPesquisarLocadora.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMPesquisarLocadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPesquisarLocadoraMouseClicked(evt);
            }
        });
        jMenuBar.add(jMPesquisarLocadora);

        jMSobre.setText("Sobre");
        jMSobre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMSobre.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSobreMouseClicked(evt);
            }
        });
        jMenuBar.add(jMSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMMeuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMMeuPerfilMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "meuPerfil");
        jMMeuPerfil.setSelected(false);
    }//GEN-LAST:event_jMMeuPerfilMouseClicked

    private void jMPesquisarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPesquisarVeiculoMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "pesquisarVeiculos");
        readJTableVeiculo();
        jMPesquisarVeiculo.setSelected(false);
    }//GEN-LAST:event_jMPesquisarVeiculoMouseClicked

    private void jMPesquisarLocadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPesquisarLocadoraMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "pesquisarLocadora");
        readJTableLocadora();   
        jMPesquisarLocadora.setSelected(false);
    }//GEN-LAST:event_jMPesquisarLocadoraMouseClicked

    private void jMSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSobreMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "sobre");
        jMSobre.setSelected(false);
       
    }//GEN-LAST:event_jMSobreMouseClicked

    private void atualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPerfilActionPerformed
 
        ClienteDAO dao = new ClienteDAO();
        Cliente c = new Cliente();
        
        c.setNome(nomePerfilCliente.getText());
        c.setEmail(emailPerfilCliente.getText());
        c.setTelefone(telefonePerfilCliente.getText());
        c.setSenha(senhaPerfilCliente.getText());
        c.setId(Integer.parseInt(idPerfilCliente.getText()));
        
        dao.update(c);

    }//GEN-LAST:event_atualizarPerfilActionPerformed

    private void excluirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPerfilActionPerformed
        
        ClienteDAO dao = new ClienteDAO();

            int e = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar a sua conta?");
            
            if(e == 0){
               dao.delete(id);
               this.dispose(); 
            }
    }//GEN-LAST:event_excluirPerfilActionPerformed

    private void buscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMarcaActionPerformed
        readJTableVeiculoMarca(jTFbuscarMarca.getText());
    }//GEN-LAST:event_buscarMarcaActionPerformed

    private void buscarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarModeloActionPerformed
         readJTableVeiculoModelo(jTFbuscarModelo.getText());
    }//GEN-LAST:event_buscarModeloActionPerformed

    private void bucarTodosVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarTodosVeiculosActionPerformed
        readJTableVeiculo();
    }//GEN-LAST:event_bucarTodosVeiculosActionPerformed

    private void buscarIdLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdLocadoraActionPerformed
        readJTableVeiculoIdLocadora(Integer.parseInt(jTFbuscarIdLocadora.getText()));
    }//GEN-LAST:event_buscarIdLocadoraActionPerformed

    private void buscarAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAnoActionPerformed
        readJTableVeiculoAno(jTFbuscarAno.getText());
    }//GEN-LAST:event_buscarAnoActionPerformed

    private void buscarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCorActionPerformed
        readJTableVeiculoCor(jTFbuscarCor.getText());
    }//GEN-LAST:event_buscarCorActionPerformed

    private void buscarMotocicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMotocicletasActionPerformed
        readJTableVeiculoMotocicleta();
    }//GEN-LAST:event_buscarMotocicletasActionPerformed

    private void buscarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCarrosActionPerformed
        readJTableVeiculoCarros();
    }//GEN-LAST:event_buscarCarrosActionPerformed

    private void buscarIdVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdVeiculoActionPerformed
        readJTableVeiculoIdVeiculo(Integer.parseInt(jTFbuscarIdVeiculo.getText()));
    }//GEN-LAST:event_buscarIdVeiculoActionPerformed

    private void buscarLocadoraNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLocadoraNomeActionPerformed
       readJTableLocadoraNome(jTFbuscarLocadoraNome.getText());
    }//GEN-LAST:event_buscarLocadoraNomeActionPerformed

    private void buscarLocadoraCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLocadoraCNPJActionPerformed
        readJTableLocadoraCNPJ(jTFbuscarLocadoraCNPJ.getText());
    }//GEN-LAST:event_buscarLocadoraCNPJActionPerformed

    private void BuscarLocadoraLocadoraIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLocadoraLocadoraIdActionPerformed
        readJTableLocadoraIdLocadora(Integer.parseInt(jTFBuscarLocadoraIdLocadora.getText()));
    }//GEN-LAST:event_BuscarLocadoraLocadoraIdActionPerformed

    private void bucarTodasLocadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarTodasLocadorasActionPerformed
       readJTableLocadora();
    }//GEN-LAST:event_bucarTodasLocadorasActionPerformed

    private void jTFbuscarIdVeiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarIdVeiculoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
             readJTableVeiculoIdVeiculo(Integer.parseInt(jTFbuscarIdVeiculo.getText()));
        }
    }//GEN-LAST:event_jTFbuscarIdVeiculoKeyPressed

    private void jTFbuscarIdLocadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarIdLocadoraKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER) {
            readJTableVeiculoIdLocadora(Integer.parseInt(jTFbuscarIdLocadora.getText()));
        }
    }//GEN-LAST:event_jTFbuscarIdLocadoraKeyPressed

    private void jTFbuscarMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarMarcaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            readJTableVeiculoMarca(jTFbuscarMarca.getText());
        }
    }//GEN-LAST:event_jTFbuscarMarcaKeyPressed

    private void jTFbuscarModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarModeloKeyPressed
         if (evt.getKeyCode() == evt.VK_ENTER) {
            readJTableVeiculoModelo(jTFbuscarModelo.getText());
        }
    }//GEN-LAST:event_jTFbuscarModeloKeyPressed

    private void jTFbuscarAnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarAnoKeyPressed
         if (evt.getKeyCode() == evt.VK_ENTER) {
             readJTableVeiculoAno(jTFbuscarAno.getText());
        }
    }//GEN-LAST:event_jTFbuscarAnoKeyPressed

    private void jTFbuscarCorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarCorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
              readJTableVeiculoCor(jTFbuscarCor.getText());
        }
    }//GEN-LAST:event_jTFbuscarCorKeyPressed

    private void jTFBuscarLocadoraIdLocadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarLocadoraIdLocadoraKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
               readJTableLocadoraIdLocadora(Integer.parseInt(jTFBuscarLocadoraIdLocadora.getText()));
        }
    }//GEN-LAST:event_jTFBuscarLocadoraIdLocadoraKeyPressed

    private void jTFbuscarLocadoraNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarLocadoraNomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
               readJTableLocadoraNome(jTFbuscarLocadoraNome.getText());
        }
    }//GEN-LAST:event_jTFbuscarLocadoraNomeKeyPressed

    private void jTFbuscarLocadoraCNPJKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscarLocadoraCNPJKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
               readJTableLocadoraCNPJ(jTFbuscarLocadoraCNPJ.getText());
        }
    }//GEN-LAST:event_jTFbuscarLocadoraCNPJKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente c = new Cliente();
                new PrincipalCliente(c).setVisible(true);
             //   testarPerfil();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarLocadoraLocadoraId;
    private javax.swing.JButton atualizarPerfil;
    private javax.swing.JButton bucarTodasLocadoras;
    private javax.swing.JButton bucarTodosVeiculos;
    private javax.swing.JButton buscarAno;
    private javax.swing.JButton buscarCarros;
    private javax.swing.JButton buscarCor;
    private javax.swing.JButton buscarIdLocadora;
    private javax.swing.JButton buscarIdVeiculo;
    private javax.swing.JButton buscarLocadoraCNPJ;
    private javax.swing.JButton buscarLocadoraNome;
    private javax.swing.JButton buscarMarca;
    private javax.swing.JButton buscarModelo;
    private javax.swing.JButton buscarMotocicletas;
    private javax.swing.JTextField emailPerfilCliente;
    private javax.swing.JButton excluirPerfil;
    private javax.swing.JLabel idPerfilCliente;
    private javax.swing.JLabel jLEmail1;
    private javax.swing.JLabel jLNome1;
    private javax.swing.JLabel jLNome2;
    private javax.swing.JLabel jLSenha1;
    private javax.swing.JLabel jLTelefonePerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenu jMMeuPerfil;
    private javax.swing.JMenu jMPesquisarLocadora;
    private javax.swing.JMenu jMPesquisarVeiculo;
    private javax.swing.JMenu jMSobre;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPLocadora;
    private javax.swing.JPanel jPMeuPerfil;
    private javax.swing.JPanel jPSobre;
    private javax.swing.JPanel jPVeiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFBuscarLocadoraIdLocadora;
    private javax.swing.JTextField jTFbuscarAno;
    private javax.swing.JTextField jTFbuscarCor;
    private javax.swing.JTextField jTFbuscarIdLocadora;
    private javax.swing.JTextField jTFbuscarIdVeiculo;
    private javax.swing.JTextField jTFbuscarLocadoraCNPJ;
    private javax.swing.JTextField jTFbuscarLocadoraNome;
    private javax.swing.JTextField jTFbuscarMarca;
    private javax.swing.JTextField jTFbuscarModelo;
    private javax.swing.JTable jTableLocadora;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField nomePerfilCliente;
    private javax.swing.JPasswordField senhaPerfilCliente;
    private javax.swing.JFormattedTextField telefonePerfilCliente;
    // End of variables declaration//GEN-END:variables

    public void limparPesquisaVeiculo(){
      
        jTFbuscarAno.setText(null);
        jTFbuscarCor.setText(null);
        jTFbuscarIdLocadora.setText(null);
        jTFbuscarIdVeiculo.setText(null);
        jTFbuscarMarca.setText(null);
        jTFbuscarModelo.setText(null);
        
    }
    public void limparPesquisaLocadora(){
      
        jTFBuscarLocadoraIdLocadora.setText(null);
        jTFbuscarLocadoraCNPJ.setText(null);
        jTFbuscarLocadoraNome.setText(null);
        
    }

      public void readJTableVeiculo(){
          
            DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
            modelo.setNumRows(0);
            VeiculoDAO VeiculoDao = new VeiculoDAO();
            
            for(Veiculo v: VeiculoDao.read())
                // pegar valor da lista e ir 'setando' no veiculo
                
                modelo.addRow(new Object[]{
                    v.getId(),
                    v.getId_locadora(),
                    v.getVeiculo(),
                    v.getMarca(),
                    v.getModelo(),
                    v.getPrecoDia(),
                    v.getAno(),
                    v.getCor(),
                    v.getCombustivel(),
                    v.getMotor(),
                    v.getPlaca()
                });
      }
      
    public void readJTableLocadora(){
          
            DefaultTableModel modelo = (DefaultTableModel) jTableLocadora.getModel();
            modelo.setNumRows(0);
            LocadoraDAO LocadoraDao = new LocadoraDAO();
            
            for(Locadora l: LocadoraDao.read())
                // pegar valor da lista e ir 'setando' no veiculo
                
                modelo.addRow(new Object[]{
                    l.getId(),
                    l.getNome(),
                    l.getCnpj(),
                    l.getTelefone(),
                    l.getEmail()
                });
      }

    public void readJTableLocadoraIdLocadora(int idLocadora) {
        
        limparPesquisaLocadora();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableLocadora.getModel();
         modelo.setNumRows(0);
         LocadoraDAO ldao = new LocadoraDAO();

        ldao.readForIdLocadora(idLocadora).forEach((l) -> {
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNome(),
                l.getCnpj(),
                l.getTelefone(),
                l.getEmail()
            });
        });

    }
    
     public void readJTableLocadoraNome(String nome) {
         
        limparPesquisaLocadora();
         
        DefaultTableModel modelo = (DefaultTableModel) jTableLocadora.getModel();
         modelo.setNumRows(0);
         LocadoraDAO ldao = new LocadoraDAO();

        ldao.readForNome(nome).forEach((l) -> {
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNome(),
                l.getCnpj(),
                l.getTelefone(),
                l.getEmail()
            });
        });
    }
     
     public void readJTableLocadoraCNPJ(String cnpj) {
        limparPesquisaLocadora();
         DefaultTableModel modelo = (DefaultTableModel) jTableLocadora.getModel();
         modelo.setNumRows(0);
         LocadoraDAO ldao = new LocadoraDAO();

        ldao.readForCnpj(cnpj).forEach((l) -> {
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNome(),
                l.getCnpj(),
                l.getTelefone(),
                l.getEmail()
            });
        });

    }
    
    public void readJTableVeiculoMarca(String marca) {
        
        limparPesquisaVeiculo();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForMarca(marca).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
    public void readJTableVeiculoModelo(String modelo) {
        
        limparPesquisaVeiculo();
        
        DefaultTableModel model = (DefaultTableModel) jTableVeiculo.getModel();
        model.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForModelo(modelo).forEach((v) -> {
            model.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     public void readJTableVeiculoCarros() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForCarros().forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     public void readJTableVeiculoIdVeiculo(int idVeiculo) {
         
        limparPesquisaVeiculo();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForIdVeiculo(idVeiculo).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     
     public void readJTableVeiculoIdLocadora(int idLocadora) {
         
        limparPesquisaVeiculo();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForIdLocadora(idLocadora).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     public void readJTableVeiculoMotocicleta() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForMotocicleta().forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(), 
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     
     public void readJTableVeiculoAno(String ano) {
            
        limparPesquisaVeiculo();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForAno(ano).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
     public void readJTableVeiculoCor(String cor) {
        
         limparPesquisaVeiculo();
         
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForCor(cor).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getId_locadora(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
    public void setPerfil(Cliente c){
        
        nomePerfilCliente.setText(c.getNome());
        emailPerfilCliente.setText(c.getEmail());
        telefonePerfilCliente.setText(c.getTelefone());
        senhaPerfilCliente.setText(c.getSenha());
        idPerfilCliente.setText(String.valueOf(c.getId()));
        
    }
    
}
