/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Veiculo;
import classes.Locadora;
import connection.LocadoraDAO;
import connection.VeiculoDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import validacao.ValidaVeiculo;

public class PrincipalLocadora extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public static int id = 0; 
    
    public PrincipalLocadora(Locadora l) {
        id = l.getId();
        
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));

        readJTable(id);
        
        setPerfil(l);      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPMeuPerfil = new javax.swing.JPanel();
        jPMeuPerfil1 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLNome2 = new javax.swing.JLabel();
        nomePerfilLocadora = new javax.swing.JTextField();
        jLEmail2 = new javax.swing.JLabel();
        emailPerfilLocadora = new javax.swing.JTextField();
        jLTelefonePerfil1 = new javax.swing.JLabel();
        telefonePerfilLocadora = new javax.swing.JFormattedTextField();
        jLEstado2 = new javax.swing.JLabel();
        estadoPerfilLocadora = new javax.swing.JTextField();
        jLCidade2 = new javax.swing.JLabel();
        cidadePerfilLocadora = new javax.swing.JTextField();
        jLBairro2 = new javax.swing.JLabel();
        bairroPerfilLocadora = new javax.swing.JTextField();
        jLSenha2 = new javax.swing.JLabel();
        senhaPerfilLocadora = new javax.swing.JPasswordField();
        excluirPerfil1 = new javax.swing.JButton();
        atualizarPerfil1 = new javax.swing.JButton();
        jLNome3 = new javax.swing.JLabel();
        IdPerfilLocadora = new javax.swing.JLabel();
        jPPesquisar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPSobre = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPCadastrar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jCBVeiculo = new javax.swing.JComboBox<>();
        jLMarca = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jLModelo = new javax.swing.JLabel();
        jTFModelo = new javax.swing.JTextField();
        jLCor = new javax.swing.JLabel();
        jTFCor = new javax.swing.JTextField();
        jLAno = new javax.swing.JLabel();
        jTFAno = new javax.swing.JTextField();
        jLCombustivel = new javax.swing.JLabel();
        jTFCombustivel = new javax.swing.JTextField();
        jLPlaca = new javax.swing.JLabel();
        jTFPlaca = new javax.swing.JTextField();
        jCBMotor = new javax.swing.JComboBox<>();
        jLMotor = new javax.swing.JLabel();
        jLPreco = new javax.swing.JLabel();
        jTFPreco = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFbuscarMarca = new javax.swing.JTextField();
        buscarMarca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTFbuscarModelo = new javax.swing.JTextField();
        buscarModelo = new javax.swing.JButton();
        buscarCarros = new javax.swing.JButton();
        buscarMotocicletas = new javax.swing.JButton();
        bucarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMMeuPerfil = new javax.swing.JMenu();
        jMCadastrarVeiculo = new javax.swing.JMenu();
        jMPesquisarVeiculos = new javax.swing.JMenu();
        jMSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jLayeredPane4.setPreferredSize(new java.awt.Dimension(266, 253));

        jLNome2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLNome2.setText("Nome");

        jLEmail2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLEmail2.setText("E-mail");

        jLTelefonePerfil1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLTelefonePerfil1.setText("Telefone");

        try {
            telefonePerfilLocadora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLEstado2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLEstado2.setText("Estado");

        jLCidade2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLCidade2.setText("Cidade");

        jLBairro2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLBairro2.setText("Bairro");

        jLSenha2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLSenha2.setText("Senha");

        excluirPerfil1.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        excluirPerfil1.setText("EXCLUIR CONTA");
        excluirPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPerfil1ActionPerformed(evt);
            }
        });

        atualizarPerfil1.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        atualizarPerfil1.setText("ATUALIZAR");
        atualizarPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPerfil1ActionPerformed(evt);
            }
        });

        jLNome3.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLNome3.setText("ID");

        IdPerfilLocadora.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N

        jLayeredPane4.setLayer(jLNome2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(nomePerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLEmail2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(emailPerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLTelefonePerfil1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(telefonePerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLEstado2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(estadoPerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLCidade2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(cidadePerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLBairro2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(bairroPerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLSenha2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(senhaPerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(excluirPerfil1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(atualizarPerfil1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLNome3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(IdPerfilLocadora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTelefonePerfil1)
                            .addComponent(jLSenha2)
                            .addComponent(jLCidade2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addComponent(atualizarPerfil1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(excluirPerfil1)
                                .addGap(282, 282, 282))
                            .addComponent(senhaPerfilLocadora)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefonePerfilLocadora)
                                    .addComponent(cidadePerfilLocadora))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLEstado2)
                                    .addComponent(jLBairro2))
                                .addGap(30, 30, 30)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(estadoPerfilLocadora, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                                    .addComponent(bairroPerfilLocadora)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome2)
                            .addComponent(jLEmail2)
                            .addComponent(jLNome3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailPerfilLocadora, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
                            .addComponent(nomePerfilLocadora, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IdPerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLNome3)
                    .addComponent(IdPerfilLocadora, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome2)
                    .addComponent(nomePerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEmail2)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(emailPerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLTelefonePerfil1)
                                .addComponent(telefonePerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLEstado2)
                                .addComponent(estadoPerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCidade2)
                    .addComponent(cidadePerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBairro2)
                    .addComponent(bairroPerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaPerfilLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSenha2))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarPerfil1)
                    .addComponent(excluirPerfil1))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMeuPerfil1Layout = new javax.swing.GroupLayout(jPMeuPerfil1);
        jPMeuPerfil1.setLayout(jPMeuPerfil1Layout);
        jPMeuPerfil1Layout.setHorizontalGroup(
            jPMeuPerfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMeuPerfil1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
                .addGap(1222, 1222, 1222))
        );
        jPMeuPerfil1Layout.setVerticalGroup(
            jPMeuPerfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMeuPerfil1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMeuPerfilLayout = new javax.swing.GroupLayout(jPMeuPerfil);
        jPMeuPerfil.setLayout(jPMeuPerfilLayout);
        jPMeuPerfilLayout.setHorizontalGroup(
            jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2399, Short.MAX_VALUE)
            .addGroup(jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPMeuPerfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPMeuPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPMeuPerfilLayout.setVerticalGroup(
            jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
            .addGroup(jPMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPMeuPerfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPMeuPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelPrincipal.add(jPMeuPerfil, "meuPerfil");

        jLabel3.setText("pesquisar veiculo");

        javax.swing.GroupLayout jPPesquisarLayout = new javax.swing.GroupLayout(jPPesquisar);
        jPPesquisar.setLayout(jPPesquisarLayout);
        jPPesquisarLayout.setHorizontalGroup(
            jPPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisarLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel3)
                .addContainerGap(2108, Short.MAX_VALUE))
        );
        jPPesquisarLayout.setVerticalGroup(
            jPPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisarLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel3)
                .addContainerGap(905, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPPesquisar, "pesquisar");

        jLabel4.setText("sobre");

        javax.swing.GroupLayout jPSobreLayout = new javax.swing.GroupLayout(jPSobre);
        jPSobre.setLayout(jPSobreLayout);
        jPSobreLayout.setHorizontalGroup(
            jPSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSobreLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel4)
                .addContainerGap(2143, Short.MAX_VALUE))
        );
        jPSobreLayout.setVerticalGroup(
            jPSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSobreLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel4)
                .addContainerGap(915, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPSobre, "sobre");

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        jCBVeiculo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jCBVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o veículo", "Carro", "Motocicleta" }));
        jCBVeiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCBVeiculoFocusLost(evt);
            }
        });
        jCBVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBVeiculoActionPerformed(evt);
            }
        });

        jLMarca.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLMarca.setText("Marca");

        jLModelo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLModelo.setText("Modelo");

        jLCor.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLCor.setText("Cor");

        jLAno.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLAno.setText("Ano");

        jTFAno.setText("0");

        jLCombustivel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLCombustivel.setText("Combustível");

        jLPlaca.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLPlaca.setText("Placa");

        jTFPlaca.setNextFocusableComponent(cadastrar);

        jCBMotor.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jCBMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1.0", "1.4", "1.6", "1.8", "2.0", "a", "b", "c", "d", "e", "f" }));
        jCBMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMotorActionPerformed(evt);
            }
        });

        jLMotor.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLMotor.setText("Motor");

        jLPreco.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLPreco.setText("Preço p/ dia");

        jTFPreco.setText("0");

        cadastrar.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        atualizar.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        atualizar.setText("ATUALIZAR");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLModelo)
                        .addGap(49, 49, 49)
                        .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLMarca)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLCombustivel)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMotor)
                            .addComponent(jLPlaca))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBMotor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFPlaca)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLPreco)
                        .addGap(18, 18, 18)
                        .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLCor))
                .addGap(526, 526, 526))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLAno)
                            .addGap(71, 71, 71)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFCor, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jCBVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cadastrar)
                .addGap(59, 59, 59)
                .addComponent(atualizar)
                .addGap(18, 18, 18)
                .addComponent(excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jCBVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMarca))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLModelo))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPreco)
                    .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAno)
                    .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCor)
                    .addComponent(jTFCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCombustivel)
                    .addComponent(jTFCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMotor))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPlaca))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cadastrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizar)
                            .addComponent(excluir))))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jLabel1.setText("Buscar por Marca");

        jTFbuscarMarca.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N

        buscarMarca.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        buscarMarca.setText("BUSCAR");
        buscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMarcaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        jLabel2.setText("Buscar por Modelo");

        jTFbuscarModelo.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N

        buscarModelo.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        buscarModelo.setText("BUSCAR");
        buscarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarModeloActionPerformed(evt);
            }
        });

        buscarCarros.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        buscarCarros.setText("Ver somente carros");
        buscarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCarrosActionPerformed(evt);
            }
        });

        buscarMotocicletas.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        buscarMotocicletas.setText("Ver somente motocicletas");
        buscarMotocicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMotocicletasActionPerformed(evt);
            }
        });

        bucarTodos.setFont(new java.awt.Font("Noto Sans", 3, 16)); // NOI18N
        bucarTodos.setText("Ver todos os veículos");
        bucarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFbuscarModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarModelo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFbuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarMarca))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(bucarTodos)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(buscarMotocicletas)
                        .addGap(44, 44, 44)
                        .addComponent(buscarCarros)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bucarTodos)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMotocicletas)
                    .addComponent(buscarCarros))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buscarMarca))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFbuscarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarModelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Veículo", "Marca", "Modelo", "Preço", "Ano", "Cor", "Combustível", "Motor", "Placa"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPCadastrarLayout = new javax.swing.GroupLayout(jPCadastrar);
        jPCadastrar.setLayout(jPCadastrarLayout);
        jPCadastrarLayout.setHorizontalGroup(
            jPCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCadastrarLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPCadastrarLayout.setVerticalGroup(
            jPCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastrarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastrarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPCadastrar, "cadastrar");

        jMMeuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon25.png"))); // NOI18N
        jMMeuPerfil.setText("Meu perfil");
        jMMeuPerfil.setToolTipText("");
        jMMeuPerfil.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMMeuPerfil.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMMeuPerfil.setRolloverEnabled(true);
        jMMeuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMMeuPerfilMouseClicked(evt);
            }
        });
        jMenuBar.add(jMMeuPerfil);

        jMCadastrarVeiculo.setText("Cadastrar/Atualizar/Excluir Veículos");
        jMCadastrarVeiculo.setContentAreaFilled(false);
        jMCadastrarVeiculo.setFocusable(false);
        jMCadastrarVeiculo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMCadastrarVeiculo.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMCadastrarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMCadastrarVeiculoMouseClicked(evt);
            }
        });
        jMenuBar.add(jMCadastrarVeiculo);

        jMPesquisarVeiculos.setText("Pesquisar Veículo");
        jMPesquisarVeiculos.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMPesquisarVeiculos.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMPesquisarVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPesquisarVeiculosMouseClicked(evt);
            }
        });
        jMenuBar.add(jMPesquisarVeiculos);

        jMSobre.setText("Sobre");
        jMSobre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jMSobre.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jMSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSobreMouseClicked(evt);
            }
        });
        jMenuBar.add(jMSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMMeuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMMeuPerfilMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "meuPerfil");
        jMMeuPerfil.setSelected(false);
    }//GEN-LAST:event_jMMeuPerfilMouseClicked

    private void jMCadastrarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCadastrarVeiculoMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "cadastrar");
        jMCadastrarVeiculo.setSelected(false);
    }//GEN-LAST:event_jMCadastrarVeiculoMouseClicked

    private void jMPesquisarVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPesquisarVeiculosMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "pesquisar");
        jMPesquisarVeiculos.setSelected(false);
    }//GEN-LAST:event_jMPesquisarVeiculosMouseClicked

    private void jMSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSobreMouseClicked
        CardLayout cl = (CardLayout) jPanelPrincipal.getLayout();
        cl.show(jPanelPrincipal, "sobre");
        jMSobre.setSelected(false);
       
    }//GEN-LAST:event_jMSobreMouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
       
        Veiculo v = new Veiculo();
        VeiculoDAO dao = new VeiculoDAO();
        
        v.setVeiculo((String) jCBVeiculo.getSelectedItem());
        v.setMarca(jTFMarca.getText());
        v.setModelo(jTFModelo.getText());
        v.setPrecoDia(Double.parseDouble(jTFPreco.getText()));
        v.setAno(Integer.parseInt(jTFAno.getText()));
        v.setCor(jTFCor.getText());
        v.setCombustivel(jTFCombustivel.getText());
        v.setMotor((String) jCBMotor.getSelectedItem());
        v.setPlaca(jTFPlaca.getText());
        v.setId_locadora(id);
        
        if(ValidaVeiculo.validaCadastro(v) == false){
            dao.create(v);
            readJTable(id);
            limpar();
        }
        
    }//GEN-LAST:event_cadastrarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        
//        if(jTable1.getSelectedRow() != -1){
//
//            DefaultTableModel a = (DefaultTableModel) jTable1.getModel();
//            a.removeRow(jTable1.getSelectedRow());
//        }
//        limpar();
        if (jTable1.getSelectedRow() != -1) {

            Veiculo v = new Veiculo();
            VeiculoDAO dao = new VeiculoDAO();

            v.setId((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            
            dao.delete(v);

            limpar();

            readJTable(id);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        if (jTable1.getSelectedRow() != -1) {
            
            jCBVeiculo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTFMarca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jTFModelo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jTFPreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jTFAno.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            jTFCor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jTFCombustivel.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jCBMotor.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jTFPlaca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed

        Veiculo v = new Veiculo();
        VeiculoDAO dao = new VeiculoDAO();
        
        v.setVeiculo((String) jCBVeiculo.getSelectedItem());
        v.setMarca(jTFMarca.getText());
        v.setModelo(jTFModelo.getText());
        v.setPrecoDia(Double.parseDouble(jTFPreco.getText()));
        v.setAno(Integer.parseInt(jTFAno.getText()));
        v.setCor(jTFCor.getText());
        v.setCombustivel(jTFCombustivel.getText());
        v.setMotor((String) jCBMotor.getSelectedItem());
        v.setPlaca(jTFPlaca.getText());
        v.setId((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        if(ValidaVeiculo.validaCadastro(v) == false){
            dao.update(v);
            readJTable(id);
            limpar();
        }

    }//GEN-LAST:event_atualizarActionPerformed

    private void jCBMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBMotorActionPerformed

    private void jCBVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBVeiculoActionPerformed

    }//GEN-LAST:event_jCBVeiculoActionPerformed

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
      
    }//GEN-LAST:event_jPanel1FocusLost

    private void jCBVeiculoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCBVeiculoFocusLost

    }//GEN-LAST:event_jCBVeiculoFocusLost

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (jTable1.getSelectedRow() != -1) {
            
            jCBVeiculo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTFMarca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jTFModelo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jTFPreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jTFAno.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            jTFCor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jTFCombustivel.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jCBMotor.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jTFPlaca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void excluirPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPerfil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirPerfil1ActionPerformed

    private void atualizarPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPerfil1ActionPerformed
        
        LocadoraDAO dao = new LocadoraDAO();
        Locadora l = new Locadora();
        
        l.setNome(nomePerfilLocadora.getText());
        l.setEmail(emailPerfilLocadora.getText());
        l.setTelefone(telefonePerfilLocadora.getText());
        l.setSenha(senhaPerfilLocadora.getText());
        l.setId(Integer.parseInt(IdPerfilLocadora.getText()));

        dao.update(l);
        
    }//GEN-LAST:event_atualizarPerfil1ActionPerformed

    private void buscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMarcaActionPerformed
        readJTableForMarca(jTFbuscarMarca.getText(),id);
    }//GEN-LAST:event_buscarMarcaActionPerformed

    private void buscarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarModeloActionPerformed
        readJTableForModelo(jTFbuscarModelo.getText(),id);
    }//GEN-LAST:event_buscarModeloActionPerformed

    private void buscarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCarrosActionPerformed
        readJTableForCarros(id);
    }//GEN-LAST:event_buscarCarrosActionPerformed

    private void buscarMotocicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMotocicletasActionPerformed
        readJTableForMotocicleta(id);
    }//GEN-LAST:event_buscarMotocicletasActionPerformed

    private void bucarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarTodosActionPerformed
        readJTable(id);
    }//GEN-LAST:event_bucarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Locadora l = new Locadora();
                new PrincipalLocadora(l).setVisible(true);
             //   testarPerfil();
            // id = l.getId();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdPerfilLocadora;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton atualizarPerfil1;
    private javax.swing.JTextField bairroPerfilLocadora;
    private javax.swing.JButton bucarTodos;
    private javax.swing.JButton buscarCarros;
    private javax.swing.JButton buscarMarca;
    private javax.swing.JButton buscarModelo;
    private javax.swing.JButton buscarMotocicletas;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField cidadePerfilLocadora;
    private javax.swing.JTextField emailPerfilLocadora;
    private javax.swing.JTextField estadoPerfilLocadora;
    private javax.swing.JButton excluir;
    private javax.swing.JButton excluirPerfil1;
    private javax.swing.JComboBox<String> jCBMotor;
    private javax.swing.JComboBox<String> jCBVeiculo;
    private javax.swing.JLabel jLAno;
    private javax.swing.JLabel jLBairro2;
    private javax.swing.JLabel jLCidade2;
    private javax.swing.JLabel jLCombustivel;
    private javax.swing.JLabel jLCor;
    private javax.swing.JLabel jLEmail2;
    private javax.swing.JLabel jLEstado2;
    private javax.swing.JLabel jLMarca;
    private javax.swing.JLabel jLModelo;
    private javax.swing.JLabel jLMotor;
    private javax.swing.JLabel jLNome2;
    private javax.swing.JLabel jLNome3;
    private javax.swing.JLabel jLPlaca;
    private javax.swing.JLabel jLPreco;
    private javax.swing.JLabel jLSenha2;
    private javax.swing.JLabel jLTelefonePerfil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMCadastrarVeiculo;
    private javax.swing.JMenu jMMeuPerfil;
    private javax.swing.JMenu jMPesquisarVeiculos;
    private javax.swing.JMenu jMSobre;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPCadastrar;
    private javax.swing.JPanel jPMeuPerfil;
    private javax.swing.JPanel jPMeuPerfil1;
    private javax.swing.JPanel jPPesquisar;
    private javax.swing.JPanel jPSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAno;
    private javax.swing.JTextField jTFCombustivel;
    private javax.swing.JTextField jTFCor;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFPlaca;
    private javax.swing.JTextField jTFPreco;
    private javax.swing.JTextField jTFbuscarMarca;
    private javax.swing.JTextField jTFbuscarModelo;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomePerfilLocadora;
    private javax.swing.JPasswordField senhaPerfilLocadora;
    private javax.swing.JFormattedTextField telefonePerfilLocadora;
    // End of variables declaration//GEN-END:variables

    public void limpar(){

        jCBMotor.setSelectedIndex(0);
        jCBVeiculo.setSelectedIndex(0);
        
        jTFAno.setText(null);
        jTFCombustivel.setText(null);
        jTFCor.setText(null);
        jTFMarca.setText(null);
        jTFModelo.setText(null);
        jTFPreco.setText(null);
        jTFPlaca.setText(null);

    }
      
      public void testarPerfil(Locadora l){
//          
//          nome1.setText(l.getNome());
//          senha1.setText(l.getSenha());
//          telefone1.setText(l.getTelefone());
//          email1.setText(l.getNome());
//          cnpj1.setText(l.getCnpj());
//          estado1.setText(l.getEndereco().getEstado());
//          cidade1.setText(l.getEndereco().getCidade());
//          bairro1.setText(l.getEndereco().getBairro());
               
      }

      public void readJTable(int cod){
          cod = id;
          
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setNumRows(0);
            VeiculoDAO VeiculoDao = new VeiculoDAO();
            
            for(Veiculo v: VeiculoDao.read(cod))
                // pegar valor da lista e ir 'setando' no veiculo
                
                modelo.addRow(new Object[]{
                    v.getId(),
                    v.getVeiculo(),
                    v.getMarca(),
                    v.getModelo(),
                    v.getPrecoDia(),
                    v.getAno(),
                    v.getCor(),
                    v.getCombustivel(),
                    v.getMotor(),
                    v.getPlaca()
                });
                  DefaultTableModel a = (DefaultTableModel) jTable1.getModel();
      }

//    public void readJTableForDesc(String desc) {
//        
//        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
//        modelo.setNumRows(0);
//        VeiculoDAO vdao = new VeiculoDAO();
//
//        vdao.readForDesc(desc).forEach((v) -> {
//            modelo.addRow(new Object[]{
//                v.getId(),
//                v.getVeiculo(),
//                v.getMarca(),
//                v.getModelo(),
//                v.getPrecoDia(),
//                v.getAno(),
//                v.getCor(),
//                v.getCombustivel(),
//                v.getMotor(),
//                v.getPlaca()
//            });
//        });
//
//    }
    
    public void setPerfil(Locadora l){
           
        IdPerfilLocadora.setText(String.valueOf(l.getId()));
        nomePerfilLocadora.setText(l.getNome());
        emailPerfilLocadora.setText(l.getEmail());
        telefonePerfilLocadora.setText(l.getTelefone());
        senhaPerfilLocadora.setText(l.getSenha());
        
    }
    
     public void readJTableForMarca(String marca, int cod) {
        
         cod = id;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForMarca(marca,id).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
    public void readJTableForModelo(String modelo, int id) {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForModelo(modelo,id).forEach((v) -> {
            model.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     public void readJTableForCarros(int id) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForCarros(id).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
     
     public void readJTableForMotocicleta(int id) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        vdao.readForMotocicleta(id).forEach((v) -> {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getVeiculo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecoDia(),
                v.getAno(),
                v.getCor(),
                v.getCombustivel(),
                v.getMotor(),
                v.getPlaca()
            });
        });

    }
    
}
